//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetaleSklad
    {
        public int SkladID { get; set; }
        public int DetaleID { get; set; }
        public Nullable<int> Count { get; set; }
    
        public virtual Detale Detale { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
